<?php

namespace App\Enums;

class MetaEnum
{
    // ALL KEYS META
    const KEY_GROUP_TYPE = 'GROUP_TYPE';
    const KEY_CONTACT_TYPE = 'CONTACT_TYPE';
    const KEY_CUSTOMER_STATS = 'CUSTOMER_STATS';
    // ALL VALUES META
    const VALUE_GROUP_TYPE_RESTAURANT = 'RESTAURANT';
    const VALUE_GROUP_TYPE_DEPARTMENT = 'DEPARTMENT';
    const VALUE_CONTACT_TYPE_CUSTOMER = 'CUSTOMER';
    const VALUE_CONTACT_TYPE_ACCOUNT_USER = 'ACCOUNT_USER';
    const VALUE_CUSTOMER_STATS_FAVORITE_TAG = 'Fav_Tag';
    const VALUE_CUSTOMER_STATS_TOTAL_SPENDING = 'Total_Spending';
    const VALUE_CUSTOMER_STATS_AVERAGE_BILL = 'Averag_bill';
    const VALUE_CUSTOMER_STATS_TOTAL_WALKIN = 'Total_Walk_in';
    const VALUE_CUSTOMER_STATS_TOTAL_CANCEL = 'Total_Cancel';
    const VALUE_CUSTOMER_STATS_TOTAL_BOOKING = 'Total_Booking';
    const VALUE_CUSTOMER_STATS_TOTAL_WAITING = 'TOTAL_WAITING';
    const VALUE_CUSTOMER_STATS_TOTAL_NO_SHOW = 'NO_SHOW';
    const VALUE_CUSTOMER_STATS_TOTAL_BEST_MATE = 'BEST_MATE';
    const VALUE_CUSTOMER_STATS_TOTAL_BILL = 'TOTAL_BILL';
    CONST VALUE_CUSTOMER_STATS_GROUPING = array(
        self::VALUE_CUSTOMER_STATS_FAVORITE_TAG,
        self::VALUE_CUSTOMER_STATS_TOTAL_SPENDING,
        self::VALUE_CUSTOMER_STATS_AVERAGE_BILL,
        self::VALUE_CUSTOMER_STATS_TOTAL_WALKIN
    );
    // Pich List
    const KEY_PICKLIST = "PICKLIST";
}
